'use client'

import { useState } from 'react'
import { ArrowRight, BadgeCheck, BookOpen, Brain, Compass, GraduationCap, Play, Sparkles, Users } from 'lucide-react'
import type { Card } from '@/lib/content'
import { urlFor } from '@/lib/sanity'
import EnquiryForm from './EnquiryForm'

type SiteSettings = { title?: string; heroText?: string; admissionsEmail?: string; phone?: string; address?: string } | null
type Tab = 'home' | 'programmes' | 'resources' | 'insights' | 'videos' | 'work' | 'team' | 'contact'
const tabs: { id: Tab; label: string }[] = [
  { id: 'home', label: 'Home' }, { id: 'programmes', label: 'Programmes' }, { id: 'resources', label: 'Resources' }, { id: 'insights', label: 'Insights' }, { id: 'videos', label: 'Videos' }, { id: 'work', label: 'Student work' }, { id: 'team', label: 'Team' }, { id: 'contact', label: 'Contact' },
]

function ContentCards({ items, kind }: { items: Card[]; kind: 'programme' | 'resource' | 'insight' | 'video' | 'work' }) {
  const Icon = kind === 'resource' ? BookOpen : kind === 'video' ? Play : kind === 'work' ? Sparkles : kind === 'programme' ? GraduationCap : Compass
  if (!items.length) return <div className="empty-panel">This section is being prepared. Published items from Sanity will appear here automatically.</div>
  return <div className="tab-card-grid">{items.map(item => <article className="tab-card" key={item._id}>{item.image ? <img src={urlFor(item.image) || ''} alt=""/> : <div className="tab-card-icon"><Icon size={22}/></div>}<div><h3>{item.title}</h3>{item.category && <span className="tab-category">{item.category}</span>}<p>{item.description || item.excerpt || item.summary}</p>{item.url && <a href={item.url} target="_blank" rel="noreferrer">Open <ArrowRight size={15}/></a>}</div></article>)}</div>
}

export default function LandingTabs({ settings, programmes, resources, posts, videos, work, team, testimonials }: { settings: SiteSettings; programmes: Card[]; resources: Card[]; posts: Card[]; videos: Card[]; work: Card[]; team: Card[]; testimonials: Card[] }) {
  const [active, setActive] = useState<Tab>('home')
  const choose = (tab: Tab) => { setActive(tab); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const title = settings?.title || 'Candellar Education'
  const panelTitle: Record<Exclude<Tab, 'home' | 'contact'>, [string, string]> = {
    programmes: ['Programmes', 'Focused learning support and guidance for every next step.'], resources: ['Free resources', 'Useful materials for parents and learners.'], insights: ['Family insights', 'Practical perspectives on learning and education pathways.'], videos: ['Videos', 'Watch Candellar guidance and community stories.'], work: ['Student work', 'Learner work shared with guardian consent.'], team: ['Our team', 'Educators and advisors who support Candellar families.'],
  }

  return <main><a className="skip" href="#tab-content">Skip to content</a><header className="site-nav"><div className="shell site-nav-inner"><button className="brand-lockup" onClick={() => choose('home')}><img src="/brand/logo-primary.png" alt="Candellar Education"/><span>Candellar<br/>Education</span></button><div className="tab-nav" role="tablist" aria-label="Candellar sections">{tabs.map(tab => <button key={tab.id} role="tab" aria-selected={active === tab.id} className={active === tab.id ? 'active' : ''} onClick={() => choose(tab.id)}>{tab.label}</button>)}</div></div></header>
    <div id="tab-content" className="tab-content" role="tabpanel">
      {active === 'home' && <><section className="hero hero-video-section"><div className="shell hero-grid"><div><p className="eyebrow">Learn more for less</p><h1 className="hero-title">A clearer path to your child’s <em>next chapter.</em></h1><p className="hero-copy">{settings?.heroText || 'Candellar gives families practical education guidance and confidence-building support for Singapore and international learning pathways.'}</p><div className="hero-actions"><button className="button button-primary" onClick={() => choose('contact')}>Talk to an advisor <ArrowRight size={16}/></button><button className="button button-outline" onClick={() => choose('programmes')}>Explore programmes</button></div><div className="hero-note"><BadgeCheck size={18}/><span>Friendly guidance for learners, parents, and ambitious futures.</span></div></div><div className="hero-video-wrap"><video className="hero-video" autoPlay muted loop playsInline controls preload="metadata" poster="/brand/logo-dark-bg.png"><source src="/videos/CANDELLAR%20Video.mp4" type="video/mp4"/>Your browser does not support the video tag.</video><div className="hero-video-caption"><Play size={15}/><span>Meet Candellar Education</span></div></div></div></section><section className="outcomes"><div className="shell outcomes-grid"><div className="outcome-intro"><p><strong className="block font-semibold text-[var(--navy)]">Built for confident decisions.</strong>Clear information, experienced support, and learning that feels possible.</p></div><div className="outcome"><strong>300+</strong><span>Learners supported through Candellar programmes</span></div><div className="outcome"><strong>8+ years</strong><span>Helping families navigate education choices</span></div><div className="outcome"><strong>Parent-first</strong><span>Practical guidance at every milestone</span></div></div></section><section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">How we help</p><h2>One education centre. A path that fits your family.</h2></div><p>Select a tab above to explore programmes, resources, stories, and the Candellar team—without leaving this page.</p></div><div className="grid grid-3"><article className="path-card"><div className="path-icon"><Compass/></div><h3>Find the right fit</h3><p>Understand options, timelines, and the learning environment where your child can thrive.</p></article><article className="path-card"><div className="path-icon"><Brain/></div><h3>Prepare with purpose</h3><p>Build capability through focused classes, feedback, practice, and personalised support.</p></article><article className="path-card"><div className="path-icon"><GraduationCap/></div><h3>Move forward confidently</h3><p>Keep momentum with practical advice, applications support, and progress conversations.</p></article></div></div></section></>}
      {active !== 'home' && active !== 'contact' && <section className="section tab-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Candellar Education</p><h1>{panelTitle[active][0]}</h1></div><p>{panelTitle[active][1]}</p></div>{active === 'programmes' && <ContentCards items={programmes} kind="programme"/>}{active === 'resources' && <ContentCards items={resources} kind="resource"/>}{active === 'insights' && <ContentCards items={posts} kind="insight"/>}{active === 'videos' && <ContentCards items={videos} kind="video"/>}{active === 'work' && <ContentCards items={work} kind="work"/>}{active === 'team' && (team.length ? <div className="team-tab-grid">{team.map(member => <article className="team-tab-card" key={member._id}>{member.image ? <img src={urlFor(member.image) || ''} alt={member.name || ''}/> : <div className="team-avatar"><Users size={28}/></div>}<div><h2>{member.name || member.title}</h2><p className="team-role">{member.role}</p>{member.bio && <p>{member.bio}</p>}</div></article>)}</div> : <div className="empty-panel">Your published team members will appear here automatically.</div>)}</div></section>}
      {active === 'contact' && <section className="section tab-section"><div className="shell grid grid-2 gap-8"><div className="contact-panel"><p className="eyebrow">Talk to us</p><h1>Let’s find a next step that feels right.</h1><p>Tell us about your child, their stage, and what you are considering. A Candellar team member will get back to you with practical guidance.</p><div className="contact-details"><span>{settings?.admissionsEmail || 'contact@candellarsg.com'}</span><span>{settings?.phone || '+65 9634 4183'}</span>{settings?.address && <span className="whitespace-pre-line">{settings.address}</span>}</div></div><EnquiryForm/></div></section>}
    </div><footer className="site-footer"><div className="shell flex flex-wrap items-center justify-between gap-3"><span>© {new Date().getFullYear()} {title}. Learn More For Less.</span><a href="/studio">Staff sign in</a></div></footer></main>
}
