import Link from 'next/link'
import { content } from '@/lib/content'
import { urlFor } from '@/lib/sanity'
import EnquiryForm from './components/EnquiryForm'
import FacebookFeed from './components/FacebookFeed'

function CardList({items, href, descriptionKey='summary'}:{items:any[];href:string;descriptionKey?:string}) {
  return <div className="grid grid-3">{items.slice(0,3).map(item => <Link className="card" key={item._id} href={item.slug ? `${href}/${item.slug}` : href}>
    {item.image && <img src={urlFor(item.image)} alt="" className="mb-4 h-40 w-full rounded-lg object-cover" />}
    <h3 className="text-xl font-bold">{item.title}</h3><p className="mt-2 text-slate-600">{item[descriptionKey] || item.description || item.excerpt}</p>
  </Link>)}</div>
}

export default async function HomePage() {
  const [settings, programmes, resources, posts, videos, work, team, testimonials, facebook] = await Promise.all([content.settings(),content.programmes(),content.resources(),content.posts(),content.videos(),content.work(),content.team(),content.testimonials(),content.facebook()])
  const title = settings?.title || 'Candellar Education'
  return <main>
    <a className="skip" href="#content">Skip to content</a>
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="shell flex min-h-16 items-center justify-between gap-4"><Link className="font-bold tracking-wide" href="/">CANDELLAR <span className="text-blue-700">EDUCATION</span></Link><nav className="hidden gap-5 text-sm font-semibold md:flex" aria-label="Primary"><a href="#programmes">Programmes</a><a href="#resources">Resources</a><a href="#insights">Insights</a><a href="#team">Team</a></nav><a className="button button-primary text-sm" href="#contact">Talk to us</a></div></header>
    <div id="content">
      <section className="bg-[#10233f] py-20 text-white"><div className="shell grid items-center gap-10 md:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow !text-[#f7bc38]">Candellar Education</p><h1 className="mt-4 text-5xl font-bold leading-tight md:text-6xl">{settings?.heroHeadline || 'Education pathways made clear.'}</h1><p className="mt-6 max-w-xl text-lg text-slate-200">{settings?.heroText || 'Practical academic support and family-first guidance for learners preparing for Singapore and international education opportunities.'}</p><div className="mt-8 flex flex-wrap gap-3"><a className="button button-light" href="#contact">Plan your next step</a><Link className="button border border-white/50" href="/resources">Explore free resources</Link></div></div><aside className="rounded-2xl bg-white p-6 text-[#10233f]"><p className="eyebrow">What we support</p><ul className="mt-4 grid gap-4"><li><strong>School pathways</strong><br/><span className="text-slate-600">Guidance that helps families make informed choices.</span></li><li><strong>Academic confidence</strong><br/><span className="text-slate-600">English, Maths, exams, and small-group learning.</span></li><li><strong>Every next step</strong><br/><span className="text-slate-600">From eligibility to applications and ongoing support.</span></li></ul></aside></div></section>
      <section id="programmes" className="section"><div className="shell"><p className="eyebrow">Learn with purpose</p><div className="mb-8 flex items-end justify-between gap-4"><h2 className="text-3xl font-bold">Programmes and guidance</h2><a className="font-bold text-blue-700" href="#contact">Ask which path fits →</a></div><CardList items={programmes} href="#programmes" /></div></section>
      <section id="resources" className="section section-alt"><div className="shell"><p className="eyebrow">For families</p><div className="mb-8 flex items-end justify-between"><h2 className="text-3xl font-bold">Free resources</h2><Link className="font-bold text-blue-700" href="/resources">All resources →</Link></div><CardList items={resources} href="/resources" descriptionKey="description" /></div></section>
      <section id="student-work" className="section"><div className="shell"><p className="eyebrow">Learner spotlight</p><div className="mb-8 flex items-end justify-between"><h2 className="text-3xl font-bold">Student work, celebrated thoughtfully</h2><Link className="font-bold text-blue-700" href="/student-work">View showcase →</Link></div><CardList items={work} href="/student-work" descriptionKey="description" /><p className="mt-5 text-sm text-slate-600">We publish student work only with recorded guardian approval.</p></div></section>
      <section id="insights" className="section section-alt"><div className="shell"><p className="eyebrow">Learn together</p><div className="grid gap-10 md:grid-cols-2"><div><div className="mb-5 flex justify-between"><h2 className="text-3xl font-bold">From our blog</h2><Link className="font-bold text-blue-700" href="/insights">All articles →</Link></div><CardList items={posts} href="/insights" descriptionKey="excerpt" /></div><div><div className="mb-5 flex justify-between"><h2 className="text-3xl font-bold">Watch & learn</h2><Link className="font-bold text-blue-700" href="/videos">All videos →</Link></div><CardList items={videos} href="/videos" /></div></div></div></section>
      <section id="facebook" className="section"><div className="shell"><p className="eyebrow">Stay connected</p><h2 className="mb-8 text-3xl font-bold">Candellar on Facebook</h2><FacebookFeed featured={facebook} /></div></section>
      <section id="team" className="section section-alt"><div className="shell"><p className="eyebrow">People who care</p><div className="mb-8 flex justify-between"><h2 className="text-3xl font-bold">Meet the team</h2><Link className="font-bold text-blue-700" href="/team">Our team →</Link></div><CardList items={team} href="/team" descriptionKey="role" /></div></section>
      <section className="section"><div className="shell"><p className="eyebrow">Family voices</p><div className="grid grid-3">{testimonials.slice(0,3).map(item=><blockquote className="card" key={item._id}><p className="text-lg font-medium">“{item.quote}”</p><footer className="mt-4 text-sm text-slate-600">— {item.name}</footer></blockquote>)}</div></div></section>
      <section id="contact" className="section bg-[#10233f] text-white"><div className="shell grid gap-10 md:grid-cols-2"><div><p className="eyebrow !text-[#f7bc38]">Start a conversation</p><h2 className="mt-3 text-4xl font-bold">Let’s find the right next step for your child.</h2><p className="mt-5 text-slate-200">Tell us a little about your family and an admissions team member will contact you.</p><div className="mt-8 text-slate-200"><p>{settings?.admissionsEmail || 'contact@candellareducation.com'}</p><p>{settings?.phone || 'Contact details can be updated in the CMS.'}</p><p className="mt-2 whitespace-pre-line">{settings?.address}</p></div></div><EnquiryForm /></div></section>
    </div>
    <footer className="bg-[#0b1729] py-8 text-sm text-slate-300"><div className="shell flex flex-wrap justify-between gap-3"><span>© {new Date().getFullYear()} {title}</span><Link href="/studio">Staff sign in</Link></div></footer>
  </main>
}
