import Link from 'next/link'
import { ArrowRight, BadgeCheck, BookOpen, Brain, Compass, GraduationCap, Play, Sparkles, Users } from 'lucide-react'
import { content } from '@/lib/content'
import EnquiryForm from './components/EnquiryForm'

const destinations = [
  { href: '/resources', label: 'Free resources', text: 'Useful guides and materials for families planning ahead.', icon: BookOpen, tone: 'gold' },
  { href: '/insights', label: 'Family insights', text: 'Practical articles on learning, admissions, and education choices.', icon: Compass, tone: 'blue' },
  { href: '/student-work', label: 'Student work', text: 'Celebrating learner thinking, published with guardian consent.', icon: Sparkles, tone: 'cream' },
  { href: '/team', label: 'Meet our team', text: 'The educators and advisors behind Candellar support.', icon: Users, tone: 'navy' },
]

export default async function HomePage() {
  const settings = await content.settings()
  const title = settings?.title || 'Candellar Education'

  return <main>
    <a className="skip" href="#content">Skip to content</a>
    <header className="site-nav"><div className="shell site-nav-inner"><Link className="brand-lockup" href="/"><img src="/brand/logo-primary.png" alt="Candellar Education"/><span>Candellar<br/>Education</span></Link><nav className="nav-links" aria-label="Primary"><a href="#how">How we help</a><Link href="/resources">Resources</Link><Link href="/insights">Insights</Link><Link href="/team">Team</Link></nav><a className="button button-primary" href="#contact">Talk to an advisor <ArrowRight size={16}/></a></div></header>
    <div id="content">
      <section className="hero hero-video-section"><div className="shell hero-grid"><div><p className="eyebrow">Learn more for less</p><h1 className="hero-title">A clearer path to your child’s <em>next chapter.</em></h1><p className="hero-copy">{settings?.heroText || 'Candellar gives families practical education guidance and confidence-building support for Singapore and international learning pathways.'}</p><div className="hero-actions"><a className="button button-primary" href="#contact">Plan your next step <ArrowRight size={16}/></a><a className="button button-outline" href="#how">See how we help</a></div><div className="hero-note"><BadgeCheck size={18}/><span>Friendly guidance for learners, parents, and ambitious futures.</span></div></div><div className="hero-video-wrap"><video className="hero-video" autoPlay muted loop playsInline controls preload="metadata" poster="/brand/logo-dark-bg.png" aria-label="Candellar Education introduction video"><source src="/videos/CANDELLAR%20Video.mp4" type="video/mp4"/>Your browser does not support the video tag.</video><div className="hero-video-caption"><Play size={15}/><span>Meet Candellar Education</span></div></div></div></section>
      <section className="outcomes"><div className="shell outcomes-grid"><div className="outcome-intro"><p><strong className="block font-semibold text-[var(--navy)]">Built for confident decisions.</strong>Clear information, experienced support, and learning that feels possible.</p></div><div className="outcome"><strong>300+</strong><span>Learners supported through Candellar programmes</span></div><div className="outcome"><strong>8+ years</strong><span>Helping families navigate education choices</span></div><div className="outcome"><strong>Parent-first</strong><span>Practical guidance at every milestone</span></div></div></section>
      <section id="how" className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">How we help</p><h2>One education centre. A path that fits your family.</h2></div><p>Start with a conversation, not a maze of pages. We make the next step easy to understand.</p></div><div className="grid grid-3"><article className="path-card"><div className="path-icon"><Compass/></div><h3>Find the right fit</h3><p>Understand options, timelines, and the learning environment where your child can thrive.</p></article><article className="path-card"><div className="path-icon"><Brain/></div><h3>Prepare with purpose</h3><p>Build capability through focused classes, feedback, practice, and personalised support.</p></article><article className="path-card"><div className="path-icon"><GraduationCap/></div><h3>Move forward confidently</h3><p>Keep momentum with practical advice, applications support, and progress conversations.</p></article></div></div></section>
      <section className="section section-alt"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Explore Candellar</p><h2>Choose what you would like to discover.</h2></div><p>Each area has its own focused page, so the home page stays simple and easy to navigate.</p></div><div className="destination-grid">{destinations.map(({href,label,text,icon:Icon,tone})=><Link href={href} className={`destination-card ${tone}`} key={href}><div className="destination-icon"><Icon size={22}/></div><div><h3>{label}</h3><p>{text}</p></div><span>Explore <ArrowRight size={16}/></span></Link>)}</div></div></section>
      <section id="contact" className="section"><div className="shell grid grid-2 gap-8"><div className="contact-panel"><p className="eyebrow">Talk to us</p><h2>Let’s find a next step that feels right.</h2><p>Tell us about your child, their stage, and what you are considering. A Candellar team member will get back to you with practical guidance.</p><div className="contact-details"><span>{settings?.admissionsEmail || 'contact@candellarsg.com'}</span><span>{settings?.phone || '+65 9634 4183'}</span>{settings?.address && <span className="whitespace-pre-line">{settings.address}</span>}</div></div><EnquiryForm/></div></section>
    </div>
    <footer className="site-footer"><div className="shell flex flex-wrap items-center justify-between gap-3"><span>© {new Date().getFullYear()} {title}. Learn More For Less.</span><div className="flex gap-4"><Link href="/resources">Resources</Link><Link href="/videos">Videos</Link><a href="/studio">Staff sign in</a></div></div></footer>
  </main>
}
