import Link from 'next/link'
import { ArrowRight, BadgeCheck, BookOpen, Brain, Compass, GraduationCap, Lightbulb, Play, Sparkles, Users } from 'lucide-react'
import { content, Card } from '@/lib/content'
import { urlFor } from '@/lib/sanity'
import EnquiryForm from './components/EnquiryForm'
import FacebookFeed from './components/FacebookFeed'

function ContentCards({ items, href, kind }: { items:Card[]; href:string; kind:'resources'|'insights'|'videos'|'work'|'team' }) {
  const Icon = kind === 'resources' ? BookOpen : kind === 'videos' ? Play : kind === 'team' ? Users : kind === 'work' ? Sparkles : Compass
  return <div className="grid grid-3">{items.slice(0,3).map(item => <Link className="card content-card" key={item._id} href={item.slug ? `${href}/${item.slug}` : href}>
    {item.image ? <img src={urlFor(item.image) || ''} alt="" className="h-40 w-full rounded-[14px] object-cover" /> : <div className="card-mark"><Icon size={20}/></div>}
    <h3>{item.title}</h3><p>{item.description || item.excerpt || item.summary || item.role}</p><span className="text-link">Explore <ArrowRight size={15} className="inline" /></span>
  </Link>)}</div>
}

export default async function HomePage() {
  const [settings, programmes, resources, posts, videos, work, team, testimonials, facebook] = await Promise.all([content.settings(),content.programmes(),content.resources(),content.posts(),content.videos(),content.work(),content.team(),content.testimonials(),content.facebook()])
  const title = settings?.title || 'Candellar Education'
  return <main>
    <a className="skip" href="#content">Skip to content</a>
    <header className="site-nav"><div className="shell site-nav-inner"><Link className="brand-lockup" href="/"><img src="/brand/logo-primary.png" alt="Candellar Education"/><span>Candellar<br/>Education</span></Link><nav className="nav-links" aria-label="Primary"><a href="#pathways">Pathways</a><a href="#resources">Resources</a><a href="#stories">Stories</a><a href="#team">Team</a></nav><a className="button button-primary" href="#contact">Talk to an advisor <ArrowRight size={16}/></a></div></header>
    <div id="content">
      <section className="hero"><div className="shell hero-grid"><div><p className="eyebrow">Learn more for less</p><h1 className="hero-title">A clearer path to your child’s <em>next chapter.</em></h1><p className="hero-copy">{settings?.heroText || 'Candellar gives families practical education guidance and confidence-building support for Singapore and international learning pathways.'}</p><div className="hero-actions"><a className="button button-primary" href="#contact">Plan your next step <ArrowRight size={16}/></a><Link className="button button-outline" href="/resources">Free family resources</Link></div><div className="hero-note"><BadgeCheck size={18}/><span>Friendly guidance for learners, parents, and ambitious futures.</span></div></div><div className="hero-art" aria-label="Candellar Education pathway"><div className="hero-panel"><img src="/brand/logo-dark-bg.png" alt="Candellar"/><div><h2>Education choices, made easier.</h2><p>From academic preparation to practical family guidance, every next step has a plan.</p></div></div><div className="hero-path"><Sparkles size={16} className="inline mr-1 text-amber-500"/> Your pathway starts here<span>Explore · prepare · progress</span></div></div></div></section>
      <section className="outcomes"><div className="shell outcomes-grid"><div className="outcome-intro"><p><strong className="block font-semibold text-[var(--navy)]">Built for confident decisions.</strong>Clear information, experienced support, and learning that feels possible.</p></div><div className="outcome"><strong>300+</strong><span>Learners supported through Candellar programmes</span></div><div className="outcome"><strong>8+ years</strong><span>Helping families navigate education choices</span></div><div className="outcome"><strong>Parent-first</strong><span>Practical guidance at every milestone</span></div></div></section>
      <section id="pathways" className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">How we help</p><h2>One education centre. A path that fits your family.</h2></div><p>Good education websites make choices simple. Candellar turns a complex journey into clear, supported steps.</p></div><div className="grid grid-3"><article className="path-card"><div className="path-icon"><Compass/></div><h3>Find the right fit</h3><p>Understand options, timelines, and the learning environment where your child can thrive.</p></article><article className="path-card"><div className="path-icon"><Brain/></div><h3>Prepare with purpose</h3><p>Build capability through focused classes, feedback, practice, and personalised support.</p></article><article className="path-card"><div className="path-icon"><GraduationCap/></div><h3>Move forward confidently</h3><p>Keep momentum with practical advice, applications support, and progress conversations.</p></article></div></div></section>
      <section className="section section-alt"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Programmes</p><h2>Learning built around real goals.</h2></div><a className="text-link" href="#contact">Talk through your options <ArrowRight size={15} className="inline"/></a></div><div className="grid grid-3">{programmes.slice(0,3).map((programme,index)=><article className="card content-card" key={programme._id}><div className="card-mark">{index===0?<Lightbulb size={20}/>:index===1?<Brain size={20}/>:<BookOpen size={20}/>}</div><h3>{programme.title}</h3><p>{programme.summary}</p><a className="text-link" href="#contact">Ask about this programme <ArrowRight size={15} className="inline"/></a></article>)}</div></div></section>
      <section id="resources" className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Useful from day one</p><h2>Free resources for families who like to be prepared.</h2></div><Link className="text-link" href="/resources">All resources <ArrowRight size={15} className="inline"/></Link></div><ContentCards items={resources} href="/resources" kind="resources"/></div></section>
      <section className="section trust-section"><div className="shell trust-grid"><div><p className="eyebrow">Why Candellar</p><h2>Guidance that respects both ambition and real life.</h2><p>Families do not need more noise. They need a trusted education partner who can explain the choices, prepare learners well, and stay close to progress.</p><div className="trust-list"><div><BadgeCheck size={19}/><span>Small-group learning and meaningful teacher attention</span></div><div><BadgeCheck size={19}/><span>Singapore-curriculum expertise alongside wider international pathways</span></div><div><BadgeCheck size={19}/><span>Clear, reassuring communication for parents</span></div></div></div><div className="trust-board"><div><BookOpen size={22}/><strong>Practical</strong><span>Advice families can act on.</span></div><div><Users size={22}/><strong>Personal</strong><span>Support that knows the learner behind the goal.</span></div><div><Sparkles size={22}/><strong>Progress-led</strong><span>Celebrate effort, capability, and next steps.</span></div><div><Compass size={22}/><strong>Global</strong><span>Education possibilities beyond one border.</span></div></div></div></section>
      <section id="stories" className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Stories and learning</p><h2>See what Candellar is building.</h2></div><p>Student work, useful family insights, and updates from the Candellar community.</p></div><div className="showcase"><div><h3 className="mb-4 font-[Sora] text-xl">Student work</h3><ContentCards items={work} href="/student-work" kind="work"/></div><div><h3 className="mb-4 font-[Sora] text-xl">Family insights</h3><ContentCards items={posts} href="/insights" kind="insights"/></div></div><div className="mt-10"><div className="section-heading"><div><p className="eyebrow">Watch and learn</p><h2 className="!text-2xl">Videos made for curious families.</h2></div><Link className="text-link" href="/videos">All videos <ArrowRight size={15} className="inline"/></Link></div><ContentCards items={videos} href="/videos" kind="videos"/></div></div></section>
      <section id="team" className="section section-alt"><div className="shell"><div className="section-heading"><div><p className="eyebrow">The people behind the support</p><h2>Meet the Candellar team.</h2></div><Link className="text-link" href="/team">Our team <ArrowRight size={15} className="inline"/></Link></div><ContentCards items={team} href="/team" kind="team"/></div></section>
      <section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Families first</p><h2>Confidence is something families can feel.</h2></div></div><div className="grid grid-3">{testimonials.slice(0,3).map(item=><blockquote className="card quote-card" key={item._id}><p>“{item.quote}”</p><footer>— {item.name || 'Candellar family'}</footer></blockquote>)}</div><div className="social-strip mt-8"><div><p className="eyebrow">From Facebook</p><p>Updates, webinars, student moments, and more from Candellar.</p></div><a className="button button-outline" href="https://www.facebook.com/109607668260712" target="_blank" rel="noreferrer">Visit Facebook <ArrowRight size={16}/></a></div><div className="mt-4"><FacebookFeed featured={facebook}/></div></div></section>
      <section id="contact" className="section section-alt"><div className="shell grid grid-2 gap-8"><div className="contact-panel"><p className="eyebrow">Talk to us</p><h2>Let’s find a next step that feels right.</h2><p>Tell us about your child, their stage, and what you are considering. A Candellar team member will get back to you with practical guidance.</p><div className="contact-details"><span>{settings?.admissionsEmail || 'contact@candellarsg.com'}</span><span>{settings?.phone || '+65 9634 4183'}</span>{settings?.address && <span className="whitespace-pre-line">{settings.address}</span>}</div></div><EnquiryForm/></div></section>
    </div>
    <footer className="site-footer"><div className="shell flex flex-wrap items-center justify-between gap-3"><span>© {new Date().getFullYear()} {title}. Learn More For Less.</span><div className="flex gap-4"><a href="/resources">Resources</a><a href="/studio">Staff sign in</a></div></div></footer>
  </main>
}
