import { defineField, defineType } from 'sanity'

const slug = defineField({ name:'slug', title:'Slug', type:'slug', options:{ source:'title', maxLength:96 }, validation:r=>r.required() })
const seo = [defineField({ name:'seoTitle', title:'SEO title', type:'string' }), defineField({ name:'seoDescription', title:'SEO description', type:'text', rows:3 })]
const featureOnHome = defineField({ name:'featured', title:'Feature on home page', description:'Turn on to show this item in the Home tab’s featured highlights.', type:'boolean' })
const image = (name='image', title='Image') => defineField({ name, title, type:'image', options:{ hotspot:true } })
const body = defineField({ name:'body', title:'Body', type:'array', of:[{type:'block'}] })

export const schemaTypes = [
  defineType({ name:'siteSettings', title:'Site settings', type:'document', fields:[defineField({name:'title',type:'string',initialValue:'Candellar Education'}),defineField({name:'heroHeadline',type:'string'}),defineField({name:'heroText',type:'text'}),defineField({name:'admissionsEmail',type:'string'}),defineField({name:'phone',type:'string'}),defineField({name:'address',type:'text'}),defineField({name:'facebookUrl',type:'url'}),...seo] }),
  defineType({ name:'programme', title:'Programmes tab', type:'document', fields:[defineField({name:'title',title:'Programme name',type:'string',validation:r=>r.required()}),slug,defineField({name:'summary',title:'Short card description',type:'text'}),defineField({name:'details',title:'Full programme details',type:'text',rows:8}),image('image','Card cover image'),defineField({name:'gallery',title:'Images shown after a visitor opens this programme',type:'array',of:[{type:'image',options:{hotspot:true}}]}),featureOnHome,defineField({name:'order',title:'Display order (smaller number first)',type:'number'})] }),
  defineType({ name:'resource', title:'Resources tab', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'category',type:'string'}),defineField({name:'description',type:'text'}),image('coverImage','Cover image'),defineField({name:'file',title:'Download file',type:'file'}),defineField({name:'externalUrl',title:'External link instead of a download',type:'url'}),featureOnHome,...seo] }),
  defineType({ name:'post', title:'Content tab — News & updates', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'excerpt',title:'Short preview text',type:'text'}),body,image('coverImage','Cover image'),defineField({name:'author',type:'string'}),defineField({name:'publishedAt',type:'datetime'}),defineField({name:'tags',type:'array',of:[{type:'string'}]}),featureOnHome,...seo] }),
  defineType({ name:'video', title:'Content tab — Reels & videos', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'summary',type:'text'}),defineField({name:'videoFile',title:'Upload reel video — plays inside the website',type:'file',options:{accept:'video/*'}}),defineField({name:'videoUrl',title:'Or paste a public Facebook, YouTube, or Vimeo URL',type:'url'}),image('thumbnail','Thumbnail'),defineField({name:'publishedAt',type:'datetime'}),featureOnHome,...seo] }),
  defineType({ name:'studentWork', title:'Student Work tab', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,image('media','Work image'),defineField({name:'programme',type:'string'}),defineField({name:'attribution',title:'First name or initials only',type:'string'}),defineField({name:'description',type:'text'}),defineField({name:'guardianConsent',title:'Guardian consent approved',type:'boolean',validation:r=>r.required().custom(v=>v===true || 'Consent is required before publishing')}),featureOnHome,...seo] }),
  defineType({ name:'teamMember', title:'Team tab', type:'document', fields:[defineField({name:'name',type:'string',validation:r=>r.required()}),slug,defineField({name:'role',type:'string'}),defineField({name:'bio',type:'text'}),image('portrait','Portrait'),defineField({name:'email',type:'string'}),defineField({name:'linkedin',type:'url'}),featureOnHome,defineField({name:'order',title:'Display order (smaller number first)',type:'number'})] }),
  defineType({ name:'testimonial', title:'Content tab — Parent reviews', type:'document', fields:[defineField({name:'quote',title:'Parent review',type:'text',validation:r=>r.required()}),defineField({name:'name',title:'Parent first name or initials',type:'string'}),defineField({name:'relationship',type:'string'}),image('image','Optional image'),defineField({name:'featured',title:'Feature in parent reviews',type:'boolean'})] }),
  defineType({ name:'facebookPost', title:'Community tab — Facebook posts & reels', type:'document', fields:[defineField({name:'title',title:'Internal label',type:'string'}),defineField({name:'url',title:'Facebook post or Reel URL',type:'url',validation:r=>r.required()}),image('image','Post design image'),defineField({name:'video',title:'Upload Reel video — plays on hover',type:'file',options:{accept:'video/*'}}),defineField({name:'caption',title:'Caption (visitors can expand it)',type:'text'}),defineField({name:'featured',title:'Show in Community tab',type:'boolean'})] }),
  defineType({ name:'enquiry', title:'Parent enquiries', type:'document', fields:[defineField({name:'parentName',type:'string',validation:r=>r.required()}),defineField({name:'email',type:'string',validation:r=>r.required().email()}),defineField({name:'phone',type:'string'}),defineField({name:'studentLevel',type:'string'}),defineField({name:'interest',type:'string'}),defineField({name:'message',type:'text'}),defineField({name:'marketingConsent',type:'boolean'}),defineField({name:'status',type:'string',options:{list:['New','In progress','Closed']},initialValue:'New'}),defineField({name:'receivedAt',type:'datetime'})] }),
]
