import { defineField, defineType } from 'sanity'

const slug = defineField({ name:'slug', title:'Slug', type:'slug', options:{ source:'title', maxLength:96 }, validation:r=>r.required() })
const seo = [defineField({ name:'seoTitle', title:'SEO title', type:'string' }), defineField({ name:'seoDescription', title:'SEO description', type:'text', rows:3 })]
const image = (name='image', title='Image') => defineField({ name, title, type:'image', options:{ hotspot:true } })
const body = defineField({ name:'body', title:'Body', type:'array', of:[{type:'block'}] })

export const schemaTypes = [
  defineType({ name:'siteSettings', title:'Site settings', type:'document', fields:[defineField({name:'title',type:'string',initialValue:'Candellar Education'}),defineField({name:'heroHeadline',type:'string'}),defineField({name:'heroText',type:'text'}),defineField({name:'admissionsEmail',type:'string'}),defineField({name:'phone',type:'string'}),defineField({name:'address',type:'text'}),defineField({name:'facebookUrl',type:'url'}),...seo] }),
  defineType({ name:'programme', title:'Programmes & services', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'summary',type:'text'}),image('image','Cover image'),defineField({name:'featured',type:'boolean'}),defineField({name:'order',type:'number'})] }),
  defineType({ name:'resource', title:'Free resources', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'category',type:'string'}),defineField({name:'description',type:'text'}),image('coverImage','Cover image'),defineField({name:'file',type:'file'}),defineField({name:'externalUrl',type:'url'}),defineField({name:'featured',type:'boolean'}),...seo] }),
  defineType({ name:'post', title:'Blog posts', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'excerpt',type:'text'}),body,image('coverImage','Cover image'),defineField({name:'author',type:'string'}),defineField({name:'publishedAt',type:'datetime'}),defineField({name:'tags',type:'array',of:[{type:'string'}]}),defineField({name:'featured',type:'boolean'}),...seo] }),
  defineType({ name:'video', title:'Videos', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,defineField({name:'summary',type:'text'}),defineField({name:'videoUrl',title:'YouTube, Facebook, or Vimeo URL',type:'url'}),image('thumbnail','Thumbnail'),defineField({name:'publishedAt',type:'datetime'}),defineField({name:'featured',type:'boolean'}),...seo] }),
  defineType({ name:'studentWork', title:'Student work', type:'document', fields:[defineField({name:'title',type:'string',validation:r=>r.required()}),slug,image('media','Work image'),defineField({name:'programme',type:'string'}),defineField({name:'attribution',title:'First name or initials only',type:'string'}),defineField({name:'description',type:'text'}),defineField({name:'guardianConsent',title:'Guardian consent approved',type:'boolean',validation:r=>r.required().custom(v=>v===true || 'Consent is required before publishing')}),defineField({name:'featured',type:'boolean'}),...seo] }),
  defineType({ name:'teamMember', title:'Team members', type:'document', fields:[defineField({name:'name',type:'string',validation:r=>r.required()}),slug,defineField({name:'role',type:'string'}),defineField({name:'bio',type:'text'}),image('portrait','Portrait'),defineField({name:'email',type:'string'}),defineField({name:'linkedin',type:'url'}),defineField({name:'order',type:'number'})] }),
  defineType({ name:'testimonial', title:'Testimonials', type:'document', fields:[defineField({name:'quote',type:'text',validation:r=>r.required()}),defineField({name:'name',title:'First name/initials',type:'string'}),defineField({name:'relationship',type:'string'}),image('image','Optional image'),defineField({name:'featured',type:'boolean'})] }),
  defineType({ name:'facebookPost', title:'Featured Facebook posts', type:'document', fields:[defineField({name:'title',type:'string'}),defineField({name:'url',title:'Facebook post URL',type:'url',validation:r=>r.required()}),image('image','Post design image (fallback)'),defineField({name:'caption',type:'text'}),defineField({name:'featured',type:'boolean'})] }),
  defineType({ name:'enquiry', title:'Parent enquiries', type:'document', fields:[defineField({name:'parentName',type:'string',validation:r=>r.required()}),defineField({name:'email',type:'string',validation:r=>r.required().email()}),defineField({name:'phone',type:'string'}),defineField({name:'studentLevel',type:'string'}),defineField({name:'interest',type:'string'}),defineField({name:'message',type:'text'}),defineField({name:'marketingConsent',type:'boolean'}),defineField({name:'status',type:'string',options:{list:['New','In progress','Closed']},initialValue:'New'}),defineField({name:'receivedAt',type:'datetime'})] }),
]
